name: Parallel Workflow
on: [pull_request]
jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build Debug
        run: dotnet build UnitTestProject/UnitTestProject.csproj --configuration Debug
      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: output/Debug

  build-release:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build Release
        run: dotnet build src/YourProject.csproj --configuration Release
      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: output/Release
